Blog.web/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.DomainClasses.Category;
using Blog.DomainClasses.Comment;
using Blog.DomainClasses.Post;
using Blog.DomainClasses.PostCategory;
using Blog.Services.IRepositories;
using Blog.Utilities.String;
using Blog.ViewModels.Post;
using Microsoft.AspNetCore.Http.Headers;
using Microsoft.AspNetCore.Mvc;

namespace Blog.web.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IPostTagRepository _postTagRepository;
        private readonly ICommentRepository _commentRepository;
        private readonly IPostCategoryRepository _postCategoryRepository;


        public PostController(IPostRepository postRepository, ICategoryRepository categoryRepository, IPostTagRepository postTagRepository, ICommentRepository commentRepository, IPostCategoryRepository postCategoryRepository)
        {
            _postRepository = postRepository;
            _categoryRepository = categoryRepository;
            _postTagRepository = postTagRepository;
            _commentRepository = commentRepository;
            _postCategoryRepository = postCategoryRepository;
        }

        [Route("ShowPost/{id}/{name?}")]
        public IActionResult Index(int id, string name, bool? CommentStatus = null) //نمایش پست  
        {
            Post post = _postRepository.GetPostById(id); //پیدا کردن پست  و دریافت آن از Repository

            if (post == null)
            {
                return NotFound();
            }
            _postRepository.IncreaseVisitCount(id);

            ViewPostViewModel viewPost = new ViewPostViewModel()
            {
                Post = post,
                Categories = _postCategoryRepository.GetCategoriesFromPostCategoriesByPostId(id),//دسته بندی مربوطه
                PostTags = _postTagRepository.GetPostTagByPostId(id),//برچسب های پست
                Comments = _commentRepository.GetCommentByPostId(id)//نظرات پست
            };
            if (CommentStatus != null)
            {
                ViewBag.CommentStatus = CommentStatus;
            }

            return View(viewPost);
        }
        [Route("ShowNext/{id}")]
        public IActionResult NextPost(int id,bool? CommentStatus=null) //نمایش پست  
        {
            Post post =  _postRepository.GetNextPost(id); //پیدا کردن پست  و دریافت آن از Repository

            if (post == null)
            {
                return NotFound();
            }
            _postRepository.IncreaseVisitCount(id);

            ViewPostViewModel viewPost = new ViewPostViewModel()
            {
                Post = post,
                Categories = _postCategoryRepository.GetCategoriesFromPostCategoriesByPostId(id),//دسته بندی مربوطه
                PostTags = _postTagRepository.GetPostTagByPostId(id),//برچسب های پست
                Comments =  _commentRepository.GetCommentByPostId(id)//نظرات پست
            };
            if (CommentStatus!=null)
            {
                ViewBag.CommentStatus = CommentStatus;
            }
            
            return View(viewPost);
        }
        [Route("ShowPerv/{id}")]
        public IActionResult PreviosPost(int id, bool? CommentStatus = null) //نمایش پست  
        {
            Post post = _postRepository.GetPreiviosPost(id); //پیدا کردن پست  و دریافت آن از Repository

            if (post == null)
            {
                return NotFound();
            }
            _postRepository.IncreaseVisitCount(id);

            ViewPostViewModel viewPost = new ViewPostViewModel()
            {
                Post = post,
                Categories = _postCategoryRepository.GetCategoriesFromPostCategoriesByPostId(id),//دسته بندی مربوطه
                PostTags = _postTagRepository.GetPostTagByPostId(id),//برچسب های پست
                Comments = _commentRepository.GetCommentByPostId(id)//نظرات پست
            };
            if (CommentStatus != null)
            {
                ViewBag.CommentStatus = CommentStatus;
            }

            return View(viewPost);
        }
        [Route("p/{shortkey}")]
        public IActionResult ShortLink(string shortkey)//بازگرداندن به پست توسط لینک کوتاه
        {
            Post post = _postRepository.GetPostByShortKey(shortkey);//پیدا کردن پست از روی کلمه کوتاه
            if (post == null)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index), new {id = post.PostId, name = post.Title.ToUrl()});
        }


        [HttpPost]
        public IActionResult CreateComment([Bind("PostId,ParentId,Name,Email,Subject,CommentText")] Comment comment) //ایجاد نظر
        {
            if (ModelState.IsValid)
            {
                comment.CreateDate = DateTime.Now;
                comment.IsPublish = false;
                _commentRepository.InsertComment(comment);
                _commentRepository.Save();
                return Redirect(Request.Headers["Referer"].ToString()+"?CommentStatus=true");//بازگرداندن به صفحه درخواست کننده
            }
            else
            {
                return Redirect(Request.Headers["Referer"].ToString() + "?CommentStatus=false");
            }
        }
    }
}

Blog.web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Services.IRepositories;
using Microsoft.AspNetCore.Mvc;

namespace Blog.web.Controllers
{
    public class SearchController : Controller
    {
        private readonly IPostTagRepository _postTagRepository;
        private readonly IPostRepository _postRepository;
        private readonly IOptionRepository _optionRepository;
        private int postPerPage;
        public SearchController(IPostTagRepository postTagRepository, IPostRepository postRepository, IOptionRepository optionRepository)
        {
            _postTagRepository = postTagRepository;
            _postRepository = postRepository;
            _optionRepository = optionRepository;
            postPerPage = _optionRepository.GetOption().ItemPerPage;
        }

        [Route("tag/{tag}")]
        public IActionResult Tags(string tag, int pageId = 1)//جست و جو بر اساس برچست
        {
            return View("TagSearch", _postTagRepository.GetPostByTagPagination(tag/* برچسب مورد نظر*/, pageId, postPerPage));//گرفتن دیتا ی مورد نظر از لایه سرویس و ارسال به ویو
        }
        [Route("search")]
        public IActionResult Search(string search, int pageId = 1)//جست جو بر اساس کلمه
        {
            ViewData["search"] = search;
            return View("Search", _postRepository.GetPostByWordPagination(search, pageId, postPerPage));
        }
        [Route("category/{name}")]
        public IActionResult Category(string name, int pageId = 1)//جست و جو براساس دسته بندی
        {
            return View("CategorySearch", _postRepository.GetPostByCategoryPagination(name, pageId, postPerPage));
        }
        [Route("Author/{name}")]
        public IActionResult Author(string name, int pageId = 1)
        {
            return View("AuthorSearch", _postRepository.GetPostByAuthorPagination(name.Replace("-"," "), pageId, postPerPage));
        }
        public IActionResult OtherCats(string name, int pageId = 1)//جست و جو براساس دسته بندی
        {
            return View("CategorySearch", _postRepository.GetPostExeptCategoryPagination(name, pageId, postPerPage));
        }
    }
}

Blog.web/ViewComponets/Advetise/AdvertiseViewComponent.cs
using Blog.DataLayer.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.web.ViewComponets.Advetise
{
    public class AdvertiseViewComponent:ViewComponent
    {
        private readonly BlogContext _context;
        public AdvertiseViewComponent(BlogContext contex)
        {
            _context = contex;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            try
            {
                return await Task.FromResult((IViewComponentResult)View("P_Advertise", await _context.Options.FirstOrDefaultAsync()));
            }
            catch (Exception e)
            {

                throw e;
            }
        }
    }
}

Blog.web/Views/Search/AuthorSearch.cshtml
@using System.Web
@using Blog.Utilities.Convertor
@using Blog.Utilities.String
@model Blog.ViewModels.Search.PostsPaginationForSearchViewModel

@{
    ViewData["Title"] = Model.SearchWord;
    Layout = "/Views/Shared/_Layout.cshtml";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Defult User</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Defult User</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="card col-12">
                    <div class="row mt-4">
                        <div class="col-12 col-md-12 ">
                            <div class="card card-primary">
                                <div class="card-header">
                                    <h3 class="card-title">Defult User</h3>
                                </div>
                                <ul class="nav p-0">
                                    @foreach (var item in Model.SimilarTags)
                                    {
                                        <li><a asp-controller="Search" asp-action="Tags" asp-route-tag="@item" class="btn-sm btn-outline-primary m-1">@item</a></li>
                                    }
                                </ul>
                            </div>
                        </div>
                        <div class="card mt-4 mb-4">
                            <div class="card-header">
                                کلمه جست و جو شده
                            </div>
                            <ul class="list-group list-group-flush text-primary p-0">
                                <li class="list-group-item">
                                    <label class="text-primary">@Model.SearchWord</label>
                                </li>

                            </ul>
                        </div>
                    </div>

                    <div class="col-12 col-md-8 ">
                        <div id="content">
                            @foreach (var item in Model.Posts)
                            {
                                <div class="card mb-4 ">
                                    <div class="card-body text-primary">
                                        <h4>@item.Title</h4>
                                        <hr>
                                        <img class="img-fluid img-thumbnail mx-auto d-block" src="/PostImages/@item.ImageName"
                                             alt="">
                                        <p class="text-medium text-justify">
                                            @Html.Raw(HttpUtility.HtmlDecode(item.ShortDesc))
                                        </p>
                                        <hr>
                                        <div class="row">
                                            <div class="text-medium col">
                                                <span>@item.UpdateDate.ToShamsi()</span>
                                                <span>&nbsp; | &nbsp;</span>
                                                <span class="text-justify">@item.VisitCount بار دیده شده</span>
                                            </div>
                                            <div class="col">
                                                <a asp-area="" asp-controller="Post" asp-action="Index" asp-route-id="@item.PostId" asp-route-name="@item.Title.ToUrl()" class="btn btn-sm btn-outline-primary float-left">ادامه مطلب</a>
                                            </div>

                                        </div>

                                    </div>
                                </div>
                            }
                            @if (Model.PageCount > 1)
                            {
                                <ul class="pagination mx-auto text-primary">
                                    <li @if (Model.CurrentPage == 1) { <text> class="page-item disabled" </text>  } else { <text> class="page-item" </text> }>
                                        <a class="page-link" asp-action="Author" asp-route-name="@Model.SearchWord.ToUrl()" asp-route-pageId="@(Model.CurrentPage - 1)" tabindex="-1">قبلی</a>
                                    </li>
                                    <li @if (Model.CurrentPage == 1) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                                        <a class="page-link" asp-action="Author" asp-route-name="@Model.SearchWord.ToUrl()" asp-route-pageId="1">1</a>
                                    </li>
                                    @for (int i = 2; i <= Model.PageCount - 1; i++)
                                    {
                                        <li @if (Model.CurrentPage == i) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                                            <a class="page-link" asp-action="Author" asp-route-name="@Model.SearchWord.ToUrl()" asp-route-pageId="@i">@i <span class="sr-only">(current)</span></a>
                                        </li>
                                    }
                                    <li @if (Model.CurrentPage == Model.PageCount) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                                        <a class="page-link" asp-action="Author" asp-route-name="@Model.SearchWord.ToUrl()" asp-route-pageId="@(Model.PageCount)">@Model.PageCount</a>
                                    </li>
                                    <li @if (Model.CurrentPage < Model.PageCount) { <text> class="page-item " </text>  } else { <text> class="page-item disabled" </text> }>
                                        <a class="page-link" asp-action="Author" asp-route-name="@Model.SearchWord.ToUrl()" asp-route-pageId="@(Model.CurrentPage + 1)">بعدی</a>
                                    </li>
                                </ul>
                            }
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </section>
</div>

Blog.web/Views/Search/CategorySearch.cshtml
@using System.Web
@using Blog.Utilities.Convertor
@using Blog.Utilities.String
@model Blog.ViewModels.Search.PostsPaginationForSearchViewModel

@{
    ViewData["Title"] = "Други Спортове";
}
<div class="col-12 col-lg-8 main-side">
    @if (Model.Posts.Any())
    {
        <h5 class="pl-2 mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit.</h5>
        <div class="mb-5 poster">
            <img src="~/PostImages/@Model.Posts.FirstOrDefault().ImageName" style="min-width:100%;" class="img-fluid mb-3 rounded"
                 alt="img">
            <div class="alert rounded-0">
                <h5 class="d-block border-0">@Model.Posts.FirstOrDefault().Title</h5>
                <small class="text-muted border-right pr-4">
                    <i class="fas fa-comment"></i>
                    Коментари: @Model.Posts.FirstOrDefault().Comments.Count
                </small>
                <small><a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="text-muted"><i class="fab fa-facebook"></i></a></small>
                <small>
                    <a href="https://www.linkedin.com/shareArticle?mini=true&url=@Model.Posts.FirstOrDefault().PostId&title=@Model.Posts.FirstOrDefault().Title&summary=@Model.Posts.FirstOrDefault().ShortDesc" class="text-muted mx-2">
                        <i class="fab fa-linkedin"></i>
                    </a>
                </small>
                <small><a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="text-muted" data-show-count="false" charset="utf-8"><i class="fab fa-twitter"></i></a></small>
            </div>
        </div>
        <hr class="my-5">

        <div class="row mt-5">
            @foreach (var item in Model.Posts)
            {
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card border-0 card-hover mb-3 rounded-0">
                        <div class="card-img-top">
                            <div class="overlay-card">
                                <a asp-area="" asp-controller="Post" asp-action="Index" asp-route-id="@item.PostId" asp-route-name="@item.Title.ToUrl()" class="px-4 py-2 rounded-pill">Отвори...</a>
                            </div>
                            <img src="/PostImages/@item.ImageName"
                                 class="img-fluid rounded-0 card-img" alt="">
                        </div>
                        <div class="card-body px-2 pt-2">
                            <strong>
                                <a href="#" class="card-title d-block text-justify">
                                    @item.Title
                                </a>
                            </strong>
                            <small class="card-text d-block mt-3 text-justify">
                                @if (item.ShortDesc.Length > 50)
                                {@Html.Raw(item.ShortDesc.Substring(0, 49))}
                            else
                            {@Html.Raw(item.ShortDesc)}
                                <a asp-area="" asp-controller="Post" asp-action="Index" asp-route-id="@item.PostId" asp-route-name="@item.Title.ToUrl()">
                                    READ
                                    MORE
                                </a>
                            </small>
                        </div>
                        <div class="card-footer bg-transparent border-left-0 border-right-0 border-bottom py-2 d-flex justify-content-between align-items-center px-2">
                            <small class="text-muted">
                                <i class="fas fa-comment mr-1"></i>Коментари:@item.Comments.Count
                            </small>

                            <div>
                                <small><a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="text-muted"><i class="fab fa-facebook"></i></a></small>
                                <small>
                                    <a href="https://www.linkedin.com/shareArticle?mini=true&url=@item.PostId&title=@item.Title&summary=@item.ShortDesc" class="text-muted mx-2">
                                        <i class="fab fa-linkedin"></i>
                                    </a>
                                </small>
                                <small><a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="text-muted" data-show-count="false" charset="utf-8"><i class="fab fa-twitter"></i></a></small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        @await Component.InvokeAsync("Advertise")
    }
    @*@if (Model.PageCount > 1)
        {
            <ul class="pagination mx-auto text-primary">
                <li @if (Model.CurrentPage == 1) { <text> class="page-item disabled" </text>  } else { <text> class="page-item" </text> }>
                    <a class="page-link"  asp-action="Category" asp-route-name="@Model.SearchWord" asp-route-pageId="@(Model.CurrentPage - 1)" tabindex="-1">قبلی</a>
                </li>
                <li @if (Model.CurrentPage == 1) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                    <a class="page-link" asp-action="Category" asp-route-name="@Model.SearchWord" asp-route-pageId="1">1</a>
                </li>
                @for (int i = 2; i <= Model.PageCount - 1; i++)
                {
                    <li @if (Model.CurrentPage == i) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                        <a class="page-link" asp-action="Category" asp-route-name="@Model.SearchWord" asp-route-pageId="@i">@i <span class="sr-only">(current)</span></a>
                    </li>
                }
                <li @if (Model.CurrentPage == Model.PageCount) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                    <a class="page-link" asp-action="Category" asp-route-name="@Model.SearchWord" asp-route-pageId="@(Model.PageCount)">@Model.PageCount</a>
                </li>
                <li @if (Model.CurrentPage < Model.PageCount) { <text> class="page-item " </text>  } else { <text> class="page-item disabled" </text> }>
                    <a class="page-link"  asp-action="Category" asp-route-pageId="@(Model.CurrentPage + 1)">بعدی</a>
                </li>
            </ul>
        }*@
</div>

Blog.web/Views/Search/Search.cshtml
@using System.Web
@using Blog.Utilities.Convertor
@using Blog.Utilities.String
@model Blog.ViewModels.Search.PostsPaginationForSearchViewModel

@{
    ViewData["Title"] = "Други Спортове";
}
<div class="col-12 col-lg-8 main-side">
    <hr class="my-5">
    @if (Model.Posts.Any())
    {
        <div class="row mt-5">
            @foreach (var item in Model.Posts.Take(6))
            {
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card border-0 card-hover mb-3 rounded-0">
                        <div class="card-img-top">
                            <div class="overlay-card">
                                <a asp-area="" asp-controller="Post" asp-action="Index" asp-route-id="@item.PostId" asp-route-name="@item.Title.ToUrl()" class="px-4 py-2 rounded-pill">Отвори...</a>
                            </div>
                            <img src="/PostImages/@item.ImageName"
                                 class="img-fluid rounded-0 card-img" alt="">
                        </div>
                        <div class="card-body px-2 pt-2">
                            <strong>
                                <a href="#" class="card-title d-block text-justify">
                                    @item.Title
                                </a>
                            </strong>
                            <small class="card-text d-block mt-3 text-justify">
                                @if (item.ShortDesc.Length > 50)
                                {@Html.Raw(item.ShortDesc.Substring(0, 49))}
                            else
                            {@Html.Raw(item.ShortDesc)}
                                <a asp-area="" asp-controller="Post" asp-action="Index" asp-route-id="@item.PostId" asp-route-name="@item.Title.ToUrl()">
                                    READ
                                    MORE
                                </a>
                            </small>
                        </div>
                        <div class="card-footer bg-transparent border-left-0 border-right-0 border-bottom py-2 d-flex justify-content-between align-items-center px-2">
                            <small class="text-muted">
                                <i class="fas fa-eye mr-1"></i>visit:@item.VisitCount
                            </small>

                            <div>

                                <small><a href="#" class="text-muted"><i class="fab fa-facebook"></i></a></small>
                                <small>
                                    <a href="#" class="text-muted mx-2">
                                        <i class="fab fa-linkedin"></i>
                                    </a>
                                </small>
                                <small><a href="#" class="text-muted"><i class="fab fa-twitter"></i></a></small>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    }
</div>
@*@if (Model.PageCount > 1)
    {
        <ul class="pagination mx-auto text-primary">
            <li @if (Model.CurrentPage == 1) { <text> class="page-item disabled" </text>  } else { <text> class="page-item" </text> }>
                <a class="page-link" asp-action="Search" asp-route-search="@Model.SearchWord" asp-route-pageId="@(Model.CurrentPage - 1)" tabindex="-1">قبلی</a>
            </li>
            <li @if (Model.CurrentPage == 1) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                <a class="page-link" asp-action="Search" asp-route-search="@Model.SearchWord" asp-route-pageId="1">1</a>
            </li>
            @for (int i = 2; i <= Model.PageCount - 1; i++)
            {
                <li @if (Model.CurrentPage == i) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                    <a class="page-link" asp-action="Search" asp-route-search="@Model.SearchWord" asp-route-pageId="@i">@i <span class="sr-only">(current)</span></a>
                </li>
            }
            <li @if (Model.CurrentPage == Model.PageCount) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                <a class="page-link" asp-action="Search" asp-route-search="@Model.SearchWord" asp-route-pageId="@(Model.PageCount)">@Model.PageCount</a>
            </li>
            <li @if (Model.CurrentPage < Model.PageCount) { <text> class="page-item " </text>  } else { <text> class="page-item disabled" </text> }>
                <a class="page-link" asp-action="Search" asp-route-search="@Model.SearchWord" asp-route-pageId="@(Model.CurrentPage + 1)">بعدی</a>
            </li>
        </ul>
    }*@
@*</div>

        </div>
    </div>*@

@section Scripts
        {
    <script>
        function changePage(pageId) {
            $("#pageId").val(pageId);
            $("#searchForm").submit();
        }
    </script>
}

Blog.web/Views/Search/TagSearch.cshtml
@using System.Web
@using Blog.Utilities.Convertor
@using Blog.Utilities.String
@model Blog.ViewModels.Search.PostsPaginationForSearchViewModel

@{
    ViewData["Title"] = Model.SearchWord;
}
<div class="row mt-4">
    <div class="col-12 col-md-4 ">
        <div class="card mt-4">
            <div class="card-body text-primary">
                <h5 class="card-title">برچسب های مشابه</h5>
                <ul class="nav p-0">
                    @foreach (var item in Model.SimilarTags)
                    {
                        <li><a asp-controller="Search" asp-action="Tags" asp-route-tag="@item" class="btn-sm btn-outline-primary m-1">@item</a></li>
                    }
                </ul>
            </div>
        </div>
        <div class="card mt-4 mb-4">
            <div class="card-header">
                کلمه جست و جو شده
            </div>
            <ul class="list-group list-group-flush text-primary p-0">
                <li class="list-group-item">
                    <label class="text-primary">@Model.SearchWord</label>
                </li>
               
            </ul>
        </div>
    </div>

    <div class="col-12 col-md-8 ">
        <div id="content">
            @foreach (var item in Model.Posts)
            {
                <div class="card mb-4 ">
                    <div class="card-body text-primary">
                        <h4>@item.Title</h4>
                        <hr>
                        <img class="img-fluid img-thumbnail mx-auto d-block" src="/PostImages/@item.ImageName"
                             alt="">
                        <p class="text-medium text-justify">
                            @Html.Raw(HttpUtility.HtmlDecode(item.ShortDesc))
                        </p>
                        <hr>
                        <div class="row">
                            <div class="text-medium col">
                                <span>@item.UpdateDate.ToShamsi()</span>
                                <span>&nbsp; | &nbsp;</span>
                                <span class="text-justify">@item.VisitCount  </span>
                            </div>
                            <div class="col">
                                <a asp-area="" asp-controller="Post" asp-action="Index" asp-route-id="@item.PostId" asp-route-name="@item.Title.ToUrl()" class="btn btn-sm btn-outline-primary float-left">ادامه مطلب</a>
                            </div>

                        </div>

                    </div>
                </div>
            }
            @if (Model.PageCount > 1)
            {
                <ul class="pagination mx-auto text-primary">
                    <li @if (Model.CurrentPage == 1) { <text> class="page-item disabled" </text>  } else { <text> class="page-item" </text> }>
                        <a class="page-link"  asp-action="Tags" asp-route-tag="@Model.SearchWord" asp-route-pageId="@(Model.CurrentPage - 1)" tabindex="-1">قبلی</a>
                    </li>
                    <li @if (Model.CurrentPage == 1) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                        <a class="page-link" asp-action="Tags" asp-route-tag="@Model.SearchWord" asp-route-pageId="1">1</a>
                    </li>
                    @for (int i = 2; i <= Model.PageCount - 1; i++)
                    {
                        <li @if (Model.CurrentPage == i) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                            <a class="page-link" asp-action="Tags" asp-route-tag="@Model.SearchWord" asp-route-pageId="@i">@i <span class="sr-only">(current)</span></a>
                        </li>
                    }
                    <li @if (Model.CurrentPage == Model.PageCount) { <text> class="page-item active" </text>  } else { <text> class="page-item" </text> }>
                        <a class="page-link" asp-action="Tags" asp-route-tag="@Model.SearchWord" asp-route-pageId="@(Model.PageCount)">@Model.PageCount</a>
                    </li>
                    <li @if (Model.CurrentPage < Model.PageCount) { <text> class="page-item " </text>  } else { <text> class="page-item disabled" </text> }>
                        <a class="page-link"  asp-action="Tags" asp-route-tag="@Model.SearchWord" asp-route-pageId="@(Model.CurrentPage + 1)">بعدی</a>
                    </li>
                </ul>
            }
        </div>

    </div>
</div>