Blog.web/Areas/Admin/Controllers/SlidersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Blog.DataLayer.Context;
using Blog.DomainClasses.Slider;
using Blog.Services.IRepositories;
using Blog.Utilities.Images;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace Blog.web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class SlidersController : Controller
    {
        private readonly ISliderRepository _sliderRepository;

        public SlidersController(ISliderRepository sliderRepository)
        {
            _sliderRepository = sliderRepository;
        }

        // GET: Admin/Sliders
        public IActionResult Index()
        {
            return View(_sliderRepository.GetAllSliders().Where(q => q.HasVideoe == false));
        }
        public IActionResult Videos()
        {
            return View(_sliderRepository.GetAllSliders().Where(q => q.HasVideoe == true));
        }
        // GET: Admin/Sliders/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slider = _sliderRepository.GetSliderById(id.Value);
            if (slider == null)
            {
                return NotFound();
            }

            return View(slider);
        }

        // GET: Admin/Sliders/Create
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult CreateVideo()
        {
            return View();
        }
        // POST: Admin/Sliders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SliderId,Title,ImageName,Url,CreateDate,VisitCount,IsPublish")] Slider slider, List<IFormFile> imgFile)
        {
            if (ModelState.IsValid)
            {
                string images = "";
                if (imgFile.Count != 0)
                {
                    foreach (IFormFile img in imgFile)
                    {
                        string currentimg = Guid.NewGuid().ToString() + Path.GetExtension(img.FileName);
                        images += currentimg + ",";
                        string savePath = Path.Combine(
                            Directory.GetCurrentDirectory(), "wwwroot/SliderImages", currentimg
                        );

                        Upload uploader = new Upload();
                        await Task.Run(() => uploader.UploadImage(savePath, img));
                    }
                    slider.ImageName = images.TrimEnd(',');
                    slider.CreateDate = DateTime.Now;
                    slider.IsPublish = false;
                    slider.VisitCount = 0;

                    _sliderRepository.InsertSlider(slider);
                    _sliderRepository.Save();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "you must select one image at least");
                    return View(slider);
                }

            }
            return View(slider);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVideo([Bind("SliderId,Title,ImageName,Url,CreateDate,VisitCount,IsPublish,HasVideoe,VideoCode")] Slider slider, IFormFile imgFile)
        {
            if (ModelState.IsValid)
            {
                string images = "";
                if (imgFile != null)
                {
                    if (slider.VideoCode != null || !string.IsNullOrEmpty(slider.VideoCode))
                    {
                        ModelState.AddModelError(string.Empty, "you must select one Video or Video Code");
                        return View(slider);
                    }
                    string currentimg = Guid.NewGuid().ToString() + Path.GetExtension(imgFile.FileName);
                    images += currentimg + ",";
                    string savePath = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot/SliderImages", currentimg
                    );

                    Upload uploader = new Upload();
                    await Task.Run(() => uploader.UploadImage(savePath, imgFile));
                    slider.VideoName = images.TrimEnd(',');
                    slider.CreateDate = DateTime.Now;
                    slider.IsPublish = false;
                    slider.VisitCount = 0;
                    _sliderRepository.InsertSlider(slider);
                    _sliderRepository.Save();
                    return RedirectToAction(nameof(Videos));
                }
                else
                {
                    if (slider.VideoCode != null || !string.IsNullOrEmpty(slider.VideoCode))
                    {
                        slider.VideoName = images.TrimEnd(',');
                        slider.CreateDate = DateTime.Now;
                        slider.IsPublish = false;
                        slider.VisitCount = 0;
                        _sliderRepository.InsertSlider(slider);
                        _sliderRepository.Save();
                        return RedirectToAction(nameof(Videos));
                    }
                    ModelState.AddModelError(string.Empty, "you must select one Video at least");
                    return View(slider);
                }

            }
            return View(slider);
        }
        // GET: Admin/Sliders/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slider = _sliderRepository.GetSliderById(id.Value);
            if (slider == null)
            {
                return NotFound();
            }
            return View(slider);
        }
        public IActionResult EditVideo(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slider = _sliderRepository.GetSliderById(id.Value);
            if (slider == null)
            {
                return NotFound();
            }
            return View(slider);
        }
        // POST: Admin/Sliders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SliderId,Title,ImageName,Url,CreateDate,VisitCount,IsPublish")] Slider slider, List<IFormFile> imgFile)
        {
            if (id != slider.SliderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string images = "";
                    foreach (IFormFile img in imgFile)
                    {
                        string currentimg = Guid.NewGuid().ToString() + Path.GetExtension(img.FileName);
                        images += currentimg + ",";
                        string savePath = Path.Combine(
                            Directory.GetCurrentDirectory(), "wwwroot/SliderImages", currentimg
                        );

                        Upload uploader = new Upload();
                        await Task.Run(() => uploader.UploadImage(savePath, img));
                    }
                    var sliderinDb = _sliderRepository.GetSliderById(id);
                    if (sliderinDb.ImageName != "" && imgFile.Count > 0)
                    {
                        sliderinDb.ImageName += ",";
                    }
                    sliderinDb.ImageName += images.TrimEnd(',');
                    sliderinDb.IsPublish = slider.IsPublish;
                    sliderinDb.Title = slider.Title;
                    sliderinDb.Url = slider.Url;
                    _sliderRepository.UpdateSlider(sliderinDb);
                    _sliderRepository.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SliderExists(slider.SliderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(slider);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditVideo(int id, [Bind("SliderId,Title,ImageName,Url,CreateDate,VisitCount,IsPublish,HasVideoe,VideoCode")] Slider slider, IFormFile imgFile)
        {
            if (id != slider.SliderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string images = "";
                    if (imgFile != null)
                    {

                        string currentimg = Guid.NewGuid().ToString() + Path.GetExtension(imgFile.FileName);
                        images += currentimg + ",";
                        string savePath = Path.Combine(
                            Directory.GetCurrentDirectory(), "wwwroot/SliderImages", currentimg
                        );

                        Upload uploader = new Upload();
                        await Task.Run(() => uploader.UploadImage(savePath, imgFile));
                    }
                    var sliderinDb = _sliderRepository.GetSliderById(id);

Blog.web/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.DomainClasses.commentForSlider;
using Blog.Services.IRepositories;
using Blog.ViewModels.Gallery;
using Microsoft.AspNetCore.Mvc;

namespace Blog.web.Controllers
{
    public class SliderController : Controller
    {
        public ISliderRepository _SliderRepository;
        private readonly ICommentRepositoryForSlider _commentRepositoryForSlider;

        public SliderController(ISliderRepository sliderRepository, ICommentRepositoryForSlider commentRepositoryForSlider)
        {
            _SliderRepository = sliderRepository;
            _commentRepositoryForSlider = commentRepositoryForSlider;
        }
        [Route("Gallery/{id?}/{name?}")]
        public IActionResult index(int id = 0, string name = "")
        {
            GalleryViewModel model = new GalleryViewModel();
            model.Other = _SliderRepository.GetSliderForShow().OrderByDescending(q => q.CreateDate).ToList();
            if (id == 0)
            {
                model.Current = model.Other.FirstOrDefault();
                _SliderRepository.IncreaseVisitCount(model.Current.SliderId);
            }
            else
            {
                model.Current = model.Other.Where(q => q.SliderId == id).FirstOrDefault();
                _SliderRepository.IncreaseVisitCount(model.Current.SliderId);
            }
            model.Comments = _commentRepositoryForSlider.GetCommentBySliderId(model.Current.SliderId);
            return View(model);
        }
        [Route("Galleryg/{id}/{name}")]
        public IActionResult RedirectToSliderUrl(int id, string name)
        {
            var slide = _SliderRepository.GetSliderById(id);
            if (slide == null)
            {
                return NotFound();
            }
            _SliderRepository.IncreaseVisitCount(id);
            return Redirect(slide.Url);
        }

        [HttpPost]
        public IActionResult CreateComment([Bind("SliderId,ParentId,Name,Email,Subject,CommentText")] CommentForSlider comment) //ایجاد نظر
        {
            if (ModelState.IsValid)
            {
                comment.CreateDate = DateTime.Now;
                comment.IsPublish = false;
                _commentRepositoryForSlider.InsertComment(comment);
                _commentRepositoryForSlider.Save();
                return Redirect(Request.Headers["Referer"].ToString() + "?CommentStatus=true");//بازگرداندن به صفحه درخواست کننده
            }
            else
            {
                return Redirect(Request.Headers["Referer"].ToString() + "?CommentStatus=false");
            }
        }
    }
}

Blog.web/Views/Slider/index.cshtml
@model Blog.ViewModels.Gallery.GalleryViewModel
@{
    ViewData["Title"] = "Галерия";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-12 col-lg-8 main-side">
    @if (Model.Current != null)
    {
        <h5 class="pl-2">@Model.Current.Title</h5>

        <div class="mb-5">

            @if (Model.Current.HasVideoe && Model.Current.VideoName != null)
            {
                <div  class="carousel slide mb-3">
                    <video style="min-width:100%;max-width:100%;max-height:547px;" class="d-block w-100" controls>
                        <source src="~/SliderImages/@Model.Current.VideoName" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </div>
            }
            else
            {
                <div id="carouselExampleControls" class="carousel slide mb-3" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="~/SliderImages/@Model.Current.ImageName.stringToArray().stringToArraySelectIndex(0)" style="min-width:100%;max-width:100%;max-height:547px;" class="d-block w-100"
                                 alt="">
                        </div>
                        @foreach (var item in Model.Current.ImageName.stringToArray().Skip(1))
                        {
                            <div class="carousel-item">
                                <img src="~/SliderImages/@item" class="d-block w-100"
                                     alt="">
                            </div>
                        }
                    </div>

                    <a class="carousel-control-prev cus-slider-icon" href="#carouselExampleControls"
                       data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next cus-slider-icon" href="#carouselExampleControls"
                       data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            }


            <small class="text-muted border-right pr-4"><i class="fas fa-comment mr-1"></i>Коментари:@Model.Comments.Count</small>
            <a href="https://www.facebook.com/sharer/sharer.php?u=http://pirinskabundesliga.com/ShowPost/@Model.Current.SliderId" class="px-4 py-1 bg-primary text-white ml-lg-4"><i class="fab fa-facebook-f"></i></a>
            <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="px-4 py-1 bg-info text-white mx-2" data-show-count="false" charset="utf-8"><i class="fab fa-twitter"></i></a>
            @*<a href="#" class="px-4 py-1 bg-danger text-white">share</a>*@
        </div>

        <hr class="mb-3">
        <div class="slider">
            <div class="slider1">
                @if (Model.Current.HasVideoe == false)
                {
                    @foreach (var item in Model.Current.ImageName.stringToArray())
                    {
                        <div class="col-lg-3">
                            <div class="card border-0 card-hover mb-3">
                                <div class="card-body p-0">
                                    <div class="card-img-top">
                                        <div class="overlay-card">
                                            <a href="#" class="text-white px-3 py-1 rounded-pill"></a>
                                        </div>
                                        <img src="~/SliderImages/@item"
                                             class="img-fluid rounded" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    }
    <hr class="mt-5">

    @if (Model.Other != null & Model.Other.Any())
    {
        <div class="row">
            @foreach (var item in Model.Other)
            {
                <div class="col-12 col-lg-4">
                    <div class="card border-0 card-hover2 mb-3">
                        <div class="card-body p-2">
                            @if (item.HasVideoe)
                            {
                                <small class="text-muted"><i class="fas fa-camera"></i> 1 Video</small>

                            }
                            else
                            {
                                <small class="text-muted"><i class="fas fa-camera"></i> @item.ImageName.stringToArray().Count() Photos</small>

                            }
                            <div class="card-img-top">
                                <div class="overlay-card">

                                    <a href="~/Gallery?id=@item.SliderId&name=@item.Title" class="text-white px-3 py-1 rounded-pill">Отвори</a>

                                </div>
                                @if (item.HasVideoe && item.VideoName != null)
                                {
                                    <a href="~/Gallery?id=@item.SliderId&name=@item.Title">
                                        <video width="207" height="138" class="img-fluid rounded">
                                            <source src="~/SliderImages/@item.VideoName" type="video/mp4">
                                            Your browser does not support the video tag.
                                        </video>
                                    </a>
                                }
                                else
                                {
                                    <img src="~/SliderImages/@item.ImageName.stringToArray().stringToArraySelectIndex(0)"
                                         class="img-fluid rounded" alt="">
                                }
                            </div>
                            <small>
                                <a href="#">@item.Title</a>
                            </small>
                        </div>
                    </div>
                </div>
            }

        </div>
    }


    <img src="~/HomeStyle/img/Layer 7.png" class="img-fluid" alt="">

    <div class="my-5 d-flex justify-content-between align-items-center">
        <a href="#" class="text-dark"><i class="fas fa-arrow-left text-success mr-2"></i> Previous </a>
        <a></a>
    </div>

    <hr class="my-5">

    @if (Model.Comments != null)
    {
        <hr class="my-5">
        <h5 class="border-0 d-block text-center mb-4">@Model.Comments.Count Коментари </h5>

        @foreach (var parent in Model.Comments.Where(p => p.ParentId == null))
        {
            <div class="d-flex align-items-center">
                <img src="~/HomeStyle/img/businessman.png" class="img-fluid mr-2 align-self-start" alt="icon">

                <div>
                    <strong class="d-block">@parent.Name</strong>
                    <small class="text-muted d-block mb-2"> @parent.CreateDate</small>
                    <p class="mb-0">
                        @parent.CommentText
                        <a class="float-right" style="cursor:pointer;" onclick="answerComment(@parent.CommentId)">
                            <i class="fas fa-reply text-success"></i>
                        </a>
                    </p>
                </div>
            </div>
            @foreach (var child in Model.Comments.Where(c => c.ParentId == parent.CommentId))
            {
                <hr class="my-3">
                <div class="d-flex align-items-center ml-lg-5 mt-3">
                    @*<span><i class="fas fa-reply text-success"></i></span>*@
                    <img src="~/HomeStyle/img/businessman.png" class="img-fluid mr-2 align-self-start" alt="icon">
                    <div>
                        <strong class="d-block"> @child.Name </strong>
                        <small class="text-muted d-block mb-2"> @child.CreateDate </small>
                        <p class="mb-0"> @child.CommentText</p>
                    </div>
                </div>
            }
            <hr />
        }

    }

    <div class="my-5">
        <h5 class="border-0 mb-0"> остави коментар</h5>
        <small>
            @*At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium.*@
        </small>
        @if (ViewBag.CommentStatus != null && ViewBag.CommentStatus == true)
        {
            <div class="alert alert-success">
                <p>Благодарим Ви за Коментари!</p>
            </div>
        }
        @if (ViewBag.CommentStatus != null && ViewBag.CommentStatus == false)
        {
            <div class="alert alert-danger">
                <p>Error</p>
            </div>
        }
        <form asp-controller="Slider" asp-action="CreateComment" method="post" class="mt-3">
            <input name="SliderId" value="@Model.Current.SliderId" type="hidden">
            <input id="commentParentId" name="ParentId" type="hidden">
            <div class="row">
                <div class="form-group col-12 col-lg-6">
                    <input id="commentName" type="text" placeholder="Име *" name="Name" class="form-control">
                </div>
                <div class="form-group col-12 col-lg-6">
                    <input type="text" name="Email" placeholder="E-mail адрес *" class="form-control">
                </div>
                <div class="form-group col-12">
                    <input type="text" name="Subject" placeholder="Заглавие *" class="form-control">
                </div>
                <div class="form-group col-12">
                    <textarea name="CommentText" id="" cols="30" rows="10" class="form-control"></textarea>
                </div>
            </div>

            <div class="d-block text-center">
                <button href="#" class="btn btn-success px-5">Публикувай</button>
            </div>
        </form>
    </div>
</div>

@section Scripts
    {
    <script language="javascript">
        function answerComment(commentId) {
            $("#commentParentId").val(commentId);
            $("#commentName").focus();
        }
    </script>

}