Blog.web/ViewComponets/Footer/FooterViewComponent.cs
using Blog.DataLayer.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.web.ViewComponets.Footer
{
    public class FooterViewComponent:ViewComponent
    {
        private readonly BlogContext _context;
        public FooterViewComponent(BlogContext contex)
        {
            _context = contex;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var options = _context.Options.FirstOrDefault();
            return await Task.FromResult((IViewComponentResult)View("P_Footer", options));
        }
    }
}

Blog.web/ViewComponets/Header/HeaderViewComponent.cs
using Blog.DataLayer.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.web.ViewComponets.Header
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly BlogContext _context;
        public HeaderViewComponent(BlogContext contex)
        {
            _context = contex;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var options = _context.Options.FirstOrDefault();
            return await Task.FromResult((IViewComponentResult)View("P_Header", options));
        }
    }
}

Blog.web/Views/Shared/_AdminLayout.cshtml
@using System.Collections.Generic
@using System.Linq
@using Blog.DomainClasses
@using Blog.web.Models
@using Microsoft.AspNetCore.Identity
@model LoginViewModel
@inject SignInManager<ApplicationUser> SignInManager
@using Blog.Utilities.Convertor
@using Blog.Utilities.String
@{
    ViewData["Title"] = "ورود";
    Layout = "/Views/Shared/_Layout.cshtml";
}
<div class="row mt-4">
    <div class="col-12 col-md-4 ">
        @await Component.InvokeAsync("ShowCategorySideBar")
    </div>

    <div class="col-12 col-md-8 ">
        <div class="card mb-4 ">
            <div class="card-body text-primary">
                @RenderBody()
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @RenderSection("Scripts", required: false)
}

Blog.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-178641715-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-178641715-1');
    </script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="~/HomeStyle/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/HomeStyle/css/all.min.css">
    <link rel="stylesheet" href="~/HomeStyle/css/fontiran.css">
    <link rel="stylesheet" href="~/HomeStyle/css/slick.css">
    <link rel="stylesheet" href="~/HomeStyle/css/slick-theme.css">
    <link rel="stylesheet" href="~/HomeStyle/css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="icon" type="image/jpg" href="~/favicon.jpg" sizes="32x32">
    @RenderSection("Styles", false)
    <title>@ViewData["Title"]</title>
</head>
<body>

    <div class="modal fade" id="search">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <h5 class="text-success">Какво търсите? </h5>
                    <form asp-controller="Search" asp-action="Search" method="get">
                        <div class="form-group box-search">
                            <input type="text" class="form-control rounded-0" value="@ViewData["search"]" name="search" placeholder="Търсене...">
                            <input id="pageId" name="pageId" value="1" type="hidden">
                            <button type="submit" class="btn shadow rounded-0"><i class="fas fa-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Header -->

    @await Component.InvokeAsync("Header")

    @RenderBody()
    @await Component.InvokeAsync("TeamTables")

    <!-- Footer -->
    @await Component.InvokeAsync("Footer")
    <!-- Footer -->

    <script src="~/HomeStyle/js/jquery-3.3.1.min.js"></script>
    <script src="~/HomeStyle/js/popper.min.js"></script>
    <script src="~/HomeStyle/js/bootstrap.min.js"></script>
    <script src="~/HomeStyle/js/slick.min.js"></script>
    <script src="~/HomeStyle/js/all.min.js"></script>
    <script src="~/HomeStyle/js/main.js"></script>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v6.0"></script>
    <script>
        function ShowLeagu(id) {
            $("#teams").load("@Url.Action("ShowTeamVC","Home")?League=" + id);

        }
    </script>
    <script>
        function ShowLeagu2(id) {
          $("#teams2").load("@Url.Action("ShowTeamVC2","Home")?League=" + id);
        }
    </script>
    @RenderSection("Scripts", false)
</body>

</html>